puts "The students of my cohort at Makers Academy"
puts "-------------------"
puts "Darko Milanic"
puts "Mirco Antenucci"
puts "Marco Silvestri"
puts "Giuseppe Bellusci"
puts "Gaetano Berardi"
puts "Sam Byram"
puts "Stephen Warnock"
puts "Liam Cooper"
puts "Jason Pearce"
puts "Rodolph Austin"
puts "Tommasso Bianchi"
puts "Lewis Cook"
puts "Alex Mowatt"
puts "Luke Murphy"
puts "Nicky Ajose"
puts "Billy Sharp"
puts "Souleymane Doukara"